import { StoreConfig } from './GenericStoreParser';

/** Declarative configs for additional marketplaces handled by
 *  {@link GenericStoreParser}. Selectors are intentionally broad — BaseParser's
 *  link-based tile discovery and currency parsing do the heavy lifting — so a
 *  store redesign rarely breaks extraction. Product-link patterns are the most
 *  stable signal and drive discovery; per-store hints refine title/brand. */
const brand = ['[class*="brand" i]', '[data-testid*="brand" i]'];

export const STORE_CONFIGS: StoreConfig[] = [
  // ---- General shopping ----
  { marketplace: "Kohl's", hostPattern: /kohls\.com/, base: 'https://www.kohls.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/prd-"], a[href*="/product/"]',
    keyRegex: /prd-(\d+)/, keywordParams: ['search', 'submit-search'], brandSelectors: brand },
  { marketplace: 'JCPenney', hostPattern: /jcpenney\.com/, base: 'https://www.jcpenney.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keyRegex: /\/p\/([^/?]+)/,
    keywordParams: ['searchTerm', 'search'], brandSelectors: brand },
  { marketplace: 'Nordstrom', hostPattern: /(?<!rack\.)nordstrom\.com/, base: 'https://www.nordstrom.com',
    detailPath: /\/s\//, linkSelector: 'a[href*="/s/"]', keyRegex: /\/s\/[^/]*\/(\d+)/,
    keywordParams: ['keyword', 'q'], brandSelectors: brand },
  { marketplace: 'Nordstrom Rack', hostPattern: /nordstromrack\.com/, base: 'https://www.nordstromrack.com',
    detailPath: /\/s\//, linkSelector: 'a[href*="/s/"]', keyRegex: /\/s\/[^/]*\/(\d+)/,
    keywordParams: ['keyword', 'q'], brandSelectors: brand },
  { marketplace: "BJ's", hostPattern: /bjs\.com/, base: 'https://www.bjs.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keyRegex: /\/(\d{5,})\.product/,
    keywordParams: ['q', 'searchTerm'], brandSelectors: brand },
  { marketplace: "Sam's Club", hostPattern: /samsclub\.com/, base: 'https://www.samsclub.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keyRegex: /\/p\/[^/]*\/(\d+)/,
    keywordParams: ['searchTerm', 'q'], brandSelectors: brand },
  { marketplace: 'Newegg', hostPattern: /newegg\.com/, base: 'https://www.newegg.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keyRegex: /\/p\/([A-Za-z0-9]+)/,
    keywordParams: ['d', 'description'], tileSelectors: ['.item-cell', '[class*="item-cell"]'],
    titleSelectors: ['.item-title', '[class*="item-title"]'], priceSelectors: ['.price-current', '[class*="price"]'] },
  { marketplace: 'Bed Bath & Beyond', hostPattern: /bedbathandbeyond\.com/, base: 'https://www.bedbathandbeyond.com',
    detailPath: /\/products\//, linkSelector: 'a[href*="/products/"]', keyRegex: /\/products\/(\d+)/,
    keywordParams: ['keywords', 'q'], brandSelectors: brand },

  // ---- Clothing & shoes ----
  { marketplace: 'Old Navy', hostPattern: /oldnavy(\.gap)?\.com/, base: 'https://oldnavy.gap.com',
    detailPath: /(product\.do|\/product\/)/, linkSelector: 'a[href*="pid="], a[href*="/product/"]',
    keyRegex: /pid=(\d+)/, keywordParams: ['searchText', 'q'], brandSelectors: brand },
  { marketplace: 'Banana Republic', hostPattern: /bananarepublic(\.gap)?\.com/, base: 'https://bananarepublic.gap.com',
    detailPath: /(product\.do|\/product\/)/, linkSelector: 'a[href*="pid="], a[href*="/product/"]',
    keyRegex: /pid=(\d+)/, keywordParams: ['searchText', 'q'], brandSelectors: brand },
  { marketplace: 'Gap', hostPattern: /gap\.com/, base: 'https://www.gap.com',
    detailPath: /(product\.do|\/product\/)/, linkSelector: 'a[href*="pid="], a[href*="/product/"]',
    keyRegex: /pid=(\d+)/, keywordParams: ['searchText', 'q'], brandSelectors: brand },
  { marketplace: 'H&M', hostPattern: /hm\.com/, base: 'https://www2.hm.com',
    detailPath: /productpage/, linkSelector: 'a[href*="productpage"]', keyRegex: /productpage\.(\d+)/,
    keywordParams: ['q', 'query'], brandSelectors: brand },
  { marketplace: 'Zara', hostPattern: /zara\.com/, base: 'https://www.zara.com',
    detailPath: /p\d+\.html/, linkSelector: 'a[href*=".html"][href*="/p"]', keyRegex: /p(\d+)\.html/,
    keywordParams: ['searchTerm', 'q'] },
  { marketplace: 'ASOS', hostPattern: /asos\.com/, base: 'https://www.asos.com',
    detailPath: /\/prd\//, linkSelector: 'a[href*="/prd/"]', keyRegex: /\/prd\/(\d+)/,
    keywordParams: ['q', 'text'], brandSelectors: brand },
  { marketplace: 'DSW', hostPattern: /dsw\.com/, base: 'https://www.dsw.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keyRegex: /\/product\/[^/]*\/(\d+)/,
    keywordParams: ['q', 'searchTerm'], brandSelectors: brand },
  { marketplace: 'Foot Locker', hostPattern: /footlocker\.com/, base: 'https://www.footlocker.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keyRegex: /\/([A-Za-z0-9]+)\.html/,
    keywordParams: ['query', 'q'], brandSelectors: brand },
  { marketplace: "Dick's", hostPattern: /dickssportinggoods\.com/, base: 'https://www.dickssportinggoods.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keyRegex: /-(\d+)\.jsp/,
    keywordParams: ['searchTerm', 'q'], brandSelectors: brand },

  // ---- Home & furniture ----
  { marketplace: 'IKEA', hostPattern: /ikea\.com/, base: 'https://www.ikea.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keyRegex: /-([a-z0-9]+)\/?$/,
    keywordParams: ['q', 'query'], brandSelectors: brand },
  { marketplace: 'Ashley', hostPattern: /ashleyfurniture\.com/, base: 'https://www.ashleyfurniture.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keywordParams: ['searchTerm', 'q'], brandSelectors: brand },
  { marketplace: 'Pottery Barn', hostPattern: /potterybarn\.com/, base: 'https://www.potterybarn.com',
    detailPath: /\/products\//, linkSelector: 'a[href*="/products/"]', keyRegex: /\/products\/([^/?]+)/,
    keywordParams: ['words', 'q'], brandSelectors: brand },
  { marketplace: 'Crate & Barrel', hostPattern: /crateandbarrel\.com/, base: 'https://www.crateandbarrel.com',
    detailPath: /\/s\d+/, linkSelector: 'a[href*="/s"]', keyRegex: /\/s(\d+)/,
    keywordParams: ['searchTerm', 'q'], brandSelectors: brand },
  { marketplace: 'Container Store', hostPattern: /containerstore\.com/, base: 'https://www.containerstore.com',
    detailPath: /\/(p|s)\//, linkSelector: 'a[href*="/p/"], a[href*="/s/"]',
    keywordParams: ['q', 'productId'], brandSelectors: brand },
  { marketplace: 'Williams Sonoma', hostPattern: /williams-?sonoma\.com/, base: 'https://www.williams-sonoma.com',
    detailPath: /\/products\//, linkSelector: 'a[href*="/products/"]', keyRegex: /\/products\/([^/?]+)/,
    keywordParams: ['words', 'q'], brandSelectors: brand },

  // ---- Electronics ----
  { marketplace: 'B&H Photo', hostPattern: /bhphotovideo\.com/, base: 'https://www.bhphotovideo.com',
    detailPath: /\/c\/product\//, linkSelector: 'a[href*="/c/product/"]', keyRegex: /\/product\/(\d+)/,
    keywordParams: ['q', 'Ntt'], brandSelectors: brand },
  { marketplace: 'Micro Center', hostPattern: /microcenter\.com/, base: 'https://www.microcenter.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keyRegex: /\/product\/(\d+)/,
    keywordParams: ['Ntt', 'q'], brandSelectors: brand },
  { marketplace: 'Dell', hostPattern: /dell\.com/, base: 'https://www.dell.com',
    detailPath: /\/(shop|product|spd)\//, linkSelector: 'a[href*="/spd/"], a[href*="/product/"]',
    keywordParams: ['q', 'k'], brandSelectors: brand },
  { marketplace: 'HP', hostPattern: /hp\.com/, base: 'https://www.hp.com',
    detailPath: /\/(pdp|product)\//, linkSelector: 'a[href*="/pdp/"], a[href*="/product/"]',
    keywordParams: ['q', 'searchQuery'], brandSelectors: brand },
  { marketplace: 'Lenovo', hostPattern: /lenovo\.com/, base: 'https://www.lenovo.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keywordParams: ['q', 'text'], brandSelectors: brand },

  // ================= Batch 2 =================
  // ---- General shopping ----
  { marketplace: 'Temu', hostPattern: /temu\.com/, base: 'https://www.temu.com',
    detailPath: /-g-\d+\.html/, linkSelector: 'a[href*="-g-"]', keyRegex: /-g-(\d+)/, keywordParams: ['search_key', 'q'] },
  { marketplace: 'Uniqlo', hostPattern: /uniqlo\.com/, base: 'https://www.uniqlo.com',
    detailPath: /\/products\//, linkSelector: 'a[href*="/products/"]', keyRegex: /\/products\/(E?\d+)/, keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'SHEIN', hostPattern: /shein\.com/, base: 'https://us.shein.com',
    detailPath: /-p-\d+/, linkSelector: 'a[href*="-p-"]', keyRegex: /-p-(\d+)/, keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Academy Sports', hostPattern: /academy\.com/, base: 'https://www.academy.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keywordParams: ['text', 'q'], brandSelectors: brand },

  // ---- Home, furniture & appliances ----
  { marketplace: 'West Elm', hostPattern: /westelm\.com/, base: 'https://www.westelm.com',
    detailPath: /\/products\//, linkSelector: 'a[href*="/products/"]', keyRegex: /\/products\/([^/?]+)/, keywordParams: ['words', 'q'], brandSelectors: brand },
  { marketplace: 'CB2', hostPattern: /cb2\.com/, base: 'https://www.cb2.com',
    detailPath: /\/s\d+/, linkSelector: 'a[href*="/s"]', keyRegex: /\/s(\d+)/, keywordParams: ['searchTerm', 'q'], brandSelectors: brand },
  { marketplace: 'Overstock', hostPattern: /overstock\.com/, base: 'https://www.overstock.com',
    detailPath: /\/products\//, linkSelector: 'a[href*="/products/"]', keyRegex: /\/products\/(\d+)/, keywordParams: ['keywords', 'q'], brandSelectors: brand },
  { marketplace: 'Lamps Plus', hostPattern: /lampsplus\.com/, base: 'https://www.lampsplus.com',
    detailPath: /\/products\//, linkSelector: 'a[href*="/products/"]', keywordParams: ['qs', 'q'], brandSelectors: brand },
  { marketplace: 'Build.com', hostPattern: /build\.com/, base: 'https://www.build.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keywordParams: ['term', 'q'], brandSelectors: brand },
  { marketplace: 'LL Flooring', hostPattern: /llflooring\.com/, base: 'https://www.llflooring.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Ace Hardware', hostPattern: /acehardware\.com/, base: 'https://www.acehardware.com',
    detailPath: /\/(p|departments)\//, linkSelector: 'a[href*="/p/"], a[href*="/departments/"]', keywordParams: ['query', 'q'], brandSelectors: brand },
  { marketplace: 'True Value', hostPattern: /truevalue\.com/, base: 'https://www.truevalue.com',
    detailPath: /\/(product|p)\//, linkSelector: 'a[href*="/product/"], a[href*="/p/"]', keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Menards', hostPattern: /menards\.com/, base: 'https://www.menards.com',
    detailPath: /p-\d+/, linkSelector: 'a[href*="/p-"], a[href*="/main/p-"]', keyRegex: /p-(\d+)/, keywordParams: ['search', 'q'], brandSelectors: brand },

  // ---- Hardware, tools & home improvement ----
  { marketplace: 'Harbor Freight', hostPattern: /harborfreight\.com/, base: 'https://www.harborfreight.com',
    detailPath: /-\d+\.html/, linkSelector: 'a[href$=".html"]', keyRegex: /-(\d+)\.html/, keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Northern Tool', hostPattern: /northerntool\.com/, base: 'https://www.northerntool.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keywordParams: ['Ntt', 'q'], brandSelectors: brand },
  { marketplace: 'Tractor Supply', hostPattern: /tractorsupply\.com/, base: 'https://www.tractorsupply.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keywordParams: ['searchTerm', 'q'], brandSelectors: brand },
  { marketplace: 'Ferguson', hostPattern: /ferguson\.com/, base: 'https://www.ferguson.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keywordParams: ['keyword', 'q'], brandSelectors: brand },
  { marketplace: 'Grainger', hostPattern: /grainger\.com/, base: 'https://www.grainger.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keywordParams: ['searchQuery', 'q'], brandSelectors: brand },
  { marketplace: 'Fastenal', hostPattern: /fastenal\.com/, base: 'https://www.fastenal.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keywordParams: ['query', 'q'], brandSelectors: brand },

  // ---- Electronics & computers ----
  { marketplace: 'Apple', hostPattern: /apple\.com/, base: 'https://www.apple.com',
    detailPath: /\/shop\/(product|buy)/, linkSelector: 'a[href*="/shop/product/"], a[href*="/shop/buy"]', keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Samsung', hostPattern: /samsung\.com/, base: 'https://www.samsung.com',
    detailPath: /\/(buy|p)\//, linkSelector: 'a[href*="/buy/"], a[href*="/p/"]', keywordParams: ['searchvalue', 'q'], brandSelectors: brand },
  { marketplace: 'GameStop', hostPattern: /gamestop\.com/, base: 'https://www.gamestop.com',
    detailPath: /\/products\//, linkSelector: 'a[href*="/products/"]', keywordParams: ['q'], brandSelectors: brand },

  // ---- Clothing & shoes ----
  { marketplace: 'American Eagle', hostPattern: /(^|\.)ae\.com/, base: 'https://www.ae.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keywordParams: ['q', 'searchTerm'], brandSelectors: brand },
  { marketplace: 'Abercrombie & Fitch', hostPattern: /abercrombie\.com/, base: 'https://www.abercrombie.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keywordParams: ['searchTerm', 'q'], brandSelectors: brand },
  { marketplace: 'Lululemon', hostPattern: /lululemon\.com/, base: 'https://shop.lululemon.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keywordParams: ['Ntt', 'q'], brandSelectors: brand },
  { marketplace: 'Nike', hostPattern: /nike\.com/, base: 'https://www.nike.com',
    detailPath: /\/t\//, linkSelector: 'a[href*="/t/"]', keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Adidas', hostPattern: /adidas\.com/, base: 'https://www.adidas.com',
    detailPath: /[A-Z0-9]+\.html/, linkSelector: 'a[href$=".html"]', keyRegex: /\/([A-Za-z0-9]+)\.html/, keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Skechers', hostPattern: /skechers\.com/, base: 'https://www.skechers.com',
    detailPath: /\/style\/|\.html/, linkSelector: 'a[href*="/style/"], a[href$=".html"]', keywordParams: ['q', 'query'], brandSelectors: brand },

  // ---- Grocery & household ----
  { marketplace: 'Kroger', hostPattern: /kroger\.com/, base: 'https://www.kroger.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keywordParams: ['query', 'q'], brandSelectors: brand },
  { marketplace: 'Publix', hostPattern: /publix\.com/, base: 'https://www.publix.com',
    detailPath: /\/pd\//, linkSelector: 'a[href*="/pd/"]', keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Albertsons', hostPattern: /albertsons\.com/, base: 'https://www.albertsons.com',
    detailPath: /product-details/, linkSelector: 'a[href*="product-details"]', keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Safeway', hostPattern: /safeway\.com/, base: 'https://www.safeway.com',
    detailPath: /product-details/, linkSelector: 'a[href*="product-details"]', keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Wegmans', hostPattern: /wegmans\.com/, base: 'https://www.wegmans.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keywordParams: ['search', 'q'], brandSelectors: brand },
  { marketplace: 'Whole Foods', hostPattern: /wholefoodsmarket\.com/, base: 'https://www.wholefoodsmarket.com',
    detailPath: /\/product/, linkSelector: 'a[href*="/product"]', keywordParams: ['text', 'q'], brandSelectors: brand },
  { marketplace: "Trader Joe's", hostPattern: /traderjoes\.com/, base: 'https://www.traderjoes.com',
    detailPath: /\/pdp\//, linkSelector: 'a[href*="/pdp/"]', keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Meijer', hostPattern: /meijer\.com/, base: 'https://www.meijer.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keywordParams: ['text', 'q'], brandSelectors: brand },
  { marketplace: 'H-E-B', hostPattern: /heb\.com/, base: 'https://www.heb.com',
    detailPath: /product-detail/, linkSelector: 'a[href*="product-detail"]', keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Aldi', hostPattern: /aldi\.us/, base: 'https://www.aldi.us',
    detailPath: /\/product/, linkSelector: 'a[href*="/product"]', keywordParams: ['q'], brandSelectors: brand },

  // ---- Toys, kids, pets & specialty ----
  { marketplace: 'LEGO', hostPattern: /lego\.com/, base: 'https://www.lego.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Mattel', hostPattern: /mattel\.com/, base: 'https://shop.mattel.com',
    detailPath: /\/products\//, linkSelector: 'a[href*="/products/"]', keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Chewy', hostPattern: /chewy\.com/, base: 'https://www.chewy.com',
    detailPath: /\/dp\//, linkSelector: 'a[href*="/dp/"]', keyRegex: /\/dp\/(\d+)/, keywordParams: ['query', 'q'], brandSelectors: brand },
  { marketplace: 'Petco', hostPattern: /petco\.com/, base: 'https://www.petco.com',
    detailPath: /\/(product|p)\//, linkSelector: 'a[href*="/product/"], a[href*="/p/"]', keywordParams: ['q', 'query'], brandSelectors: brand },
  { marketplace: 'PetSmart', hostPattern: /petsmart\.com/, base: 'https://www.petsmart.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keywordParams: ['q', 'searchTerm'], brandSelectors: brand },
  { marketplace: 'QVC', hostPattern: /qvc\.com/, base: 'https://www.qvc.com',
    detailPath: /\.product\./, linkSelector: 'a[href*=".product."]', keyRegex: /\.product\.([A-Za-z0-9]+)/, keywordParams: ['keyword', 'q'], brandSelectors: brand },
  { marketplace: 'HSN', hostPattern: /hsn\.com/, base: 'https://www.hsn.com',
    detailPath: /\/products\//, linkSelector: 'a[href*="/products/"]', keywordParams: ['query', 'q'], brandSelectors: brand },
  { marketplace: 'Michaels', hostPattern: /michaels\.com/, base: 'https://www.michaels.com',
    detailPath: /\/(product|p)\//, linkSelector: 'a[href*="/product/"], a[href*="/p/"]', keywordParams: ['q'], brandSelectors: brand },
  { marketplace: 'Joann', hostPattern: /joann\.com/, base: 'https://www.joann.com',
    detailPath: /\/(product|p)\//, linkSelector: 'a[href*="/product/"], a[href*="/p/"]', keywordParams: ['q', 'searchText'], brandSelectors: brand },
];
