import { StoreConfig } from './GenericStoreParser';

/** Declarative configs for additional marketplaces handled by
 *  {@link GenericStoreParser}. Selectors are intentionally broad — BaseParser's
 *  link-based tile discovery and currency parsing do the heavy lifting — so a
 *  store redesign rarely breaks extraction. Product-link patterns are the most
 *  stable signal and drive discovery; per-store hints refine title/brand. */
const brand = ['[class*="brand" i]', '[data-testid*="brand" i]'];

export const STORE_CONFIGS: StoreConfig[] = [
  // ---- General shopping ----
  { marketplace: "Kohl's", hostPattern: /kohls\.com/, base: 'https://www.kohls.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/prd-"], a[href*="/product/"]',
    keyRegex: /prd-(\d+)/, keywordParams: ['search', 'submit-search'], brandSelectors: brand },
  { marketplace: 'JCPenney', hostPattern: /jcpenney\.com/, base: 'https://www.jcpenney.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keyRegex: /\/p\/([^/?]+)/,
    keywordParams: ['searchTerm', 'search'], brandSelectors: brand },
  { marketplace: 'Nordstrom', hostPattern: /(?<!rack\.)nordstrom\.com/, base: 'https://www.nordstrom.com',
    detailPath: /\/s\//, linkSelector: 'a[href*="/s/"]', keyRegex: /\/s\/[^/]*\/(\d+)/,
    keywordParams: ['keyword', 'q'], brandSelectors: brand },
  { marketplace: 'Nordstrom Rack', hostPattern: /nordstromrack\.com/, base: 'https://www.nordstromrack.com',
    detailPath: /\/s\//, linkSelector: 'a[href*="/s/"]', keyRegex: /\/s\/[^/]*\/(\d+)/,
    keywordParams: ['keyword', 'q'], brandSelectors: brand },
  { marketplace: "BJ's", hostPattern: /bjs\.com/, base: 'https://www.bjs.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keyRegex: /\/(\d{5,})\.product/,
    keywordParams: ['q', 'searchTerm'], brandSelectors: brand },
  { marketplace: "Sam's Club", hostPattern: /samsclub\.com/, base: 'https://www.samsclub.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keyRegex: /\/p\/[^/]*\/(\d+)/,
    keywordParams: ['searchTerm', 'q'], brandSelectors: brand },
  { marketplace: 'Newegg', hostPattern: /newegg\.com/, base: 'https://www.newegg.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keyRegex: /\/p\/([A-Za-z0-9]+)/,
    keywordParams: ['d', 'description'], tileSelectors: ['.item-cell', '[class*="item-cell"]'],
    titleSelectors: ['.item-title', '[class*="item-title"]'], priceSelectors: ['.price-current', '[class*="price"]'] },
  { marketplace: 'Bed Bath & Beyond', hostPattern: /(bedbathandbeyond|overstock)\.com/, base: 'https://www.bedbathandbeyond.com',
    detailPath: /\/products\//, linkSelector: 'a[href*="/products/"]', keyRegex: /\/products\/(\d+)/,
    keywordParams: ['keywords', 'q'], brandSelectors: brand },

  // ---- Clothing & shoes ----
  { marketplace: 'Old Navy', hostPattern: /oldnavy(\.gap)?\.com/, base: 'https://oldnavy.gap.com',
    detailPath: /(product\.do|\/product\/)/, linkSelector: 'a[href*="pid="], a[href*="/product/"]',
    keyRegex: /pid=(\d+)/, keywordParams: ['searchText', 'q'], brandSelectors: brand },
  { marketplace: 'Banana Republic', hostPattern: /bananarepublic(\.gap)?\.com/, base: 'https://bananarepublic.gap.com',
    detailPath: /(product\.do|\/product\/)/, linkSelector: 'a[href*="pid="], a[href*="/product/"]',
    keyRegex: /pid=(\d+)/, keywordParams: ['searchText', 'q'], brandSelectors: brand },
  { marketplace: 'Gap', hostPattern: /gap\.com/, base: 'https://www.gap.com',
    detailPath: /(product\.do|\/product\/)/, linkSelector: 'a[href*="pid="], a[href*="/product/"]',
    keyRegex: /pid=(\d+)/, keywordParams: ['searchText', 'q'], brandSelectors: brand },
  { marketplace: 'H&M', hostPattern: /hm\.com/, base: 'https://www2.hm.com',
    detailPath: /productpage/, linkSelector: 'a[href*="productpage"]', keyRegex: /productpage\.(\d+)/,
    keywordParams: ['q', 'query'], brandSelectors: brand },
  { marketplace: 'Zara', hostPattern: /zara\.com/, base: 'https://www.zara.com',
    detailPath: /p\d+\.html/, linkSelector: 'a[href*=".html"][href*="/p"]', keyRegex: /p(\d+)\.html/,
    keywordParams: ['searchTerm', 'q'] },
  { marketplace: 'ASOS', hostPattern: /asos\.com/, base: 'https://www.asos.com',
    detailPath: /\/prd\//, linkSelector: 'a[href*="/prd/"]', keyRegex: /\/prd\/(\d+)/,
    keywordParams: ['q', 'text'], brandSelectors: brand },
  { marketplace: 'DSW', hostPattern: /dsw\.com/, base: 'https://www.dsw.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keyRegex: /\/product\/[^/]*\/(\d+)/,
    keywordParams: ['q', 'searchTerm'], brandSelectors: brand },
  { marketplace: 'Foot Locker', hostPattern: /footlocker\.com/, base: 'https://www.footlocker.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keyRegex: /\/([A-Za-z0-9]+)\.html/,
    keywordParams: ['query', 'q'], brandSelectors: brand },
  { marketplace: "Dick's", hostPattern: /dickssportinggoods\.com/, base: 'https://www.dickssportinggoods.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keyRegex: /-(\d+)\.jsp/,
    keywordParams: ['searchTerm', 'q'], brandSelectors: brand },

  // ---- Home & furniture ----
  { marketplace: 'IKEA', hostPattern: /ikea\.com/, base: 'https://www.ikea.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keyRegex: /-([a-z0-9]+)\/?$/,
    keywordParams: ['q', 'query'], brandSelectors: brand },
  { marketplace: 'Ashley', hostPattern: /ashleyfurniture\.com/, base: 'https://www.ashleyfurniture.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keywordParams: ['searchTerm', 'q'], brandSelectors: brand },
  { marketplace: 'Pottery Barn', hostPattern: /potterybarn\.com/, base: 'https://www.potterybarn.com',
    detailPath: /\/products\//, linkSelector: 'a[href*="/products/"]', keyRegex: /\/products\/([^/?]+)/,
    keywordParams: ['words', 'q'], brandSelectors: brand },
  { marketplace: 'Crate & Barrel', hostPattern: /crateandbarrel\.com/, base: 'https://www.crateandbarrel.com',
    detailPath: /\/s\d+/, linkSelector: 'a[href*="/s"]', keyRegex: /\/s(\d+)/,
    keywordParams: ['searchTerm', 'q'], brandSelectors: brand },
  { marketplace: 'Container Store', hostPattern: /containerstore\.com/, base: 'https://www.containerstore.com',
    detailPath: /\/(p|s)\//, linkSelector: 'a[href*="/p/"], a[href*="/s/"]',
    keywordParams: ['q', 'productId'], brandSelectors: brand },
  { marketplace: 'Williams Sonoma', hostPattern: /williams-?sonoma\.com/, base: 'https://www.williams-sonoma.com',
    detailPath: /\/products\//, linkSelector: 'a[href*="/products/"]', keyRegex: /\/products\/([^/?]+)/,
    keywordParams: ['words', 'q'], brandSelectors: brand },

  // ---- Electronics ----
  { marketplace: 'B&H Photo', hostPattern: /bhphotovideo\.com/, base: 'https://www.bhphotovideo.com',
    detailPath: /\/c\/product\//, linkSelector: 'a[href*="/c/product/"]', keyRegex: /\/product\/(\d+)/,
    keywordParams: ['q', 'Ntt'], brandSelectors: brand },
  { marketplace: 'Micro Center', hostPattern: /microcenter\.com/, base: 'https://www.microcenter.com',
    detailPath: /\/product\//, linkSelector: 'a[href*="/product/"]', keyRegex: /\/product\/(\d+)/,
    keywordParams: ['Ntt', 'q'], brandSelectors: brand },
  { marketplace: 'Dell', hostPattern: /dell\.com/, base: 'https://www.dell.com',
    detailPath: /\/(shop|product|spd)\//, linkSelector: 'a[href*="/spd/"], a[href*="/product/"]',
    keywordParams: ['q', 'k'], brandSelectors: brand },
  { marketplace: 'HP', hostPattern: /hp\.com/, base: 'https://www.hp.com',
    detailPath: /\/(pdp|product)\//, linkSelector: 'a[href*="/pdp/"], a[href*="/product/"]',
    keywordParams: ['q', 'searchQuery'], brandSelectors: brand },
  { marketplace: 'Lenovo', hostPattern: /lenovo\.com/, base: 'https://www.lenovo.com',
    detailPath: /\/p\//, linkSelector: 'a[href*="/p/"]', keywordParams: ['q', 'text'], brandSelectors: brand },
];
